/** Internal desktop session credentials — not user-facing.
 *
 * In Electron the real password is a per-install random hex generated by the
 * main process and persisted to userData/aic-ade/identity.json (fetched via
 * `window.aic.getIdentity()`). DESKTOP_IDENTITY below is ONLY the non-Electron
 * dev fallback and matches the backend's DEFAULT_IDENTITY_* credentials, so
 * standalone renderer/dev builds still authenticate against a default backend.
 */
export const DESKTOP_IDENTITY = {
  username: "admin",
  password: "admin123",
} as const;

export const ENGINE_PORT = 8000;
export const INTERNAL_ENGINE_URL = `http://127.0.0.1:${ENGINE_PORT}`;
